config/routes.rb
Rails.application.routes.draw do
  get 'profiles/:id' => 'profiles#show', as: :profile

  get 'profiles' => 'profiles#index'

  resources :tweets
  devise_for :users
  resources :relationships

  root 'tweets#index'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :message, presence: true, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tweets
   has_many :relationships
   has_many :friends, through: :relationships

 has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "friend_id"
 has_many :inverse_friends, :through => :inverse_relationships, :source => :user

   validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters

   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
     :name, :username, :bio, :location) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
     :current_password, :name, :username, :bio, :location) }

 end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		@relationship = current_user.relationships.build(:friend_id => params[:friend_id])
		if @relationship.save
			flash[:notice] = "Followed successfully." redirect_to profile_path(current_user.friend_id)
		else
			flash[:notice] = "Unable to follow." redirect_to root_path

		end
	end
def destory
	@relationship = current_user.relationships.find(parmas[:id]) 
	@relationship.destroy flash[:notice] = "No longer following."
	redirect_to profile_path(current_user.id)
end

	private
	def relationship_params
		params.require(:relationship).permit(:user_id, :friend_id)
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
before_action :set_tweet, only: [:show, :edit, :update, :destroy]

before_filter :authenticate_user!

  def index
    @tweets = Tweet.all
  end

  def show
  end

  def edit
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.'}
      else
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format| 
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Post was successfully updated.' }
    else
      format.html { render :edit}
    end
  end
  end
  
  def destory
    @tweet.destroy
    respond_to do |format| 
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'}
    end
  end
  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= csrf_meta_tags %>
   </head>
<body>

<div class="pull-right">
<% if user_signed_in? %>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
<% end %>
</div>
<%= yield %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  
 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
</body>
</html>

app/views/profiles/index.html.erb
<h1>All Users</h1>
<br>
<br>
<% @users.each do |user| %>
	<%= link_to user.username, profile_path(user) %> <br>
<% end %>

app/views/profiles/show.html.erb
<div class="row">
	<div class="col-xs-4">
		<h3><%= @username %></h3>
		<br>
		<h5><%= @user.username %></h5>
		<br>
		<h5><p><%= @user.bio %></p></h5>
		<br>
		<h5><%= @user.location %></h5>
		<br>
		<h5> Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

		<br>
		<%= @user.relationships.count %>
		Following
		<br>
		<% @user.relationships.each do |relationship| %>
			<%= link_to relationship.friend.name, profile_path(relationship.friend) %> <br>
		<% end %>
		<br>
		<br>
		<%= pluralize(@user.inverse_relationships.count, "Follwer") %>
		<br>
		<% @user.inverse_friends.each do |friend| %>
			<%= link_to friend.name, profile_path(friend) %> <br>
		<% end %>
	</div>
	
	<div class="col-xs-7">
		<% @user.tweets.each do |tweet| %>
			<div class="panel-body">
				<strong><%= tweet.user.username %></strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %>ago</small>
				<br>
				<br>
				<% t = tweet.message %>
			</div>
		<% end %>
	</div>
</div>
<br>
<br>

<% if current_user.id != @user.id %>
	<% if current_user.friends.include?(@user) %>
		<%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete, class: "btn btn-danger" %>
		<%= link_to "Follow", relationships_path(:friend_id => @user), method: :post, class: "btn btn-primary" %>

	<% end %>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>

<% if @tweet.errors.any? %>
	<div class="error_explanation">
		<h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

		<ul>
			<% @tweet.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div Class="field">
	<%= f.label :message %><br>
	<%= f.text_field :message %>
</div>

<div Class="field hidden">
	<%= f.label :user_id %><br>
	<%= f.text_field :user_id, value: current_user.id %>
</div>

<div Class="actions">
	<%= f.submit "Tweet!", class: "btn btn-primary" %>
</div>

<% end %>

app/views/tweets/edit.html.erb
<h1> Editing Tweet </h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twitter Feed</h1>

<table>
	<thead>
		<tr>
			<th>Message</th>
			<th>User</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @tweets.each do |tweet| %>
		<tr>
			<td><%= tweet.message %></td>
			<td><%= tweet.user.username %></td>
			<td><%= link_to 'Show', tweet %></td>
			<td><%= link_to 'Edit', edit_tweet_path(tweet)%></td>
			<td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you Sure?'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<br>

<%=link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Message:</strong>
	<%= @tweet.message %>
</p>

<p>
	<strong>User:</strong>
	<%= @tweet.user.username %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> 
<%= link_to 'Back', tweets_path %>